enableMirror: true

logFilters:
  - code: YN0007
    level: discard
  - code: YN0013
    level: discard

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

preferAggregateCacheInfo: true

yarnPath: .yarn/releases/yarn-3.2.3.cjs
